
spring:
  datasource:
    url: jdbc:postgresql://healthcareinsuranceproject.cwb2sup9nfn5.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update