
spring:
  datasource:
    url: jdbc:postgresql://database-1.cnzfhxjaudhj.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dml-auto: update